### ISSUE TITLE
Cleanup and fixes

### ISSUE THREAD

**Issue by dgellow** [WebFreak001/DWinProgramming#2]
Hi @WebFreak001, @AndrejMitrovic,

This project is mentioned by https://wiki.dlang.org/D_for_Win32 but doesn't build for me. I would like to do some changes to the build setup (i.e: use `dub` instead of a custom build script) and also some cleanup/update of the implementation and file structure, but I'm not sure what's the license situation and if that's better to do in my own repository or in this one.

I don't know exactly what changes I would like to do as I'm using this as a way to learn D build system and have some fun with Win32 API, but in any case it would stay a translation of Charles Petzold's code to D (and I really don't expect that much change regarding the actual logic and structure).

What do you think?

**Comment by AndrejMitrovic** [comment]
From my end you are free to go ahead and do it. It would be great if the project got some well-needed attention. Maybe just fork it? If you get stuck with anything, feel free to reach out to me.

**Comment by dgellow** [comment]
Ok, thanks! :)

**Comment by WebFreak001** [comment]
I just mirrored this project because the original project went down once, but it's back up no so idk if I even need to keep the repo now :p

Will probably just keep it so others can still access it some day when they had this in their browser history or README at some point in time, but don't really want to do too much stuff with it.

@AndrejMitrovic should I just link back to your page in the README now?

**Comment by dgellow** [comment]
Would it make sense to transfer it to @dlang-community? As it is mostly something to help the community (at large) by helping people getting started on windows. Though I'm not sure what are the criteria to be part of @dlang-community or not.

**Comment by AndrejMitrovic** [comment]
Oh yeah dlang community makes sense. I guess the question is whether this code is of any interest to the community. I would imagine that the newer Windows APIs are much more interesting to people these days. For example WinRT: https://blogs.windows.com/windowsdeveloper/2020/04/30/rust-winrt-public-preview/

**Comment by WebFreak001** [comment]
we've had WinRT for years now! https://github.com/WebFreak001/dwinrt

though async was buggy and couldn't get it to work, broke a lot of stuff

**Comment by AndrejMitrovic** [comment]
Oh see, I completely out of the loop with this. That's really cool!

**Comment by AndrejMitrovic** [comment]
@dgellow still interested? If you've already started something, let me know. Otherwise I'll fix up the build at first, and then work on a dub project file.

**Comment by dgellow** [comment]
I'm still interested, yes. I spent a bit of time on it and fixed a few issues with the build, but eventually removed the `build.d` and other build scripts because I couldn't get them work correctly (I don't have in mind what were the actual errors). I'm now trying to understand how to use DUB properly to build multiple sub projects (each chapter being a project).

I'm still really new to both D and DUB, so I'm quite slow at this. And to be honest I didn't plan to do it right away and instead try to improve things little by little when I feel like it.

So please, feel free to fix things up, that will be interesting to see how things should be done properly :)

**Comment by dgellow** [comment]
@AndrejMitrovic Ok, I noticed your changes in https://github.com/AndrejMitrovic/DWinProgramming. I'm closing this issue and will instead follow your version of the repository.

So I guess that makes it the "official" version of DWinProgramming. I will update https://wiki.dlang.org/D_for_Win32 to mention it.

**Comment by AndrejMitrovic** [comment]
Thanks @dgellow!
